# Generated by Django 5.1.7 on 2025-09-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='device_brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Device Brand'),
            preserve_default=False,
        ),
    ]
