# Generated by Django 5.1.7 on 2025-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_backup_device_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='device_brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Brand'),
        ),
    ]
