# Generated by Django 5.1.7 on 2025-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note Content'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Note ID from Backup'),
        ),
    ]
