# Generated by Django 5.1.7 on 2025-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_note_content_note_note_alter_note_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body Content'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
