# Generated by Django 5.1.7 on 2025-09-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_note_note_note_body_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Name')),
                ('miui_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIUI Version')),
                ('backup_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Backup Version')),
                ('is_auto_backup', models.CharField(blank=True, max_length=50, null=True, verbose_name='Is Auto Backup')),
                ('backup_date', models.DateTimeField(blank=True, null=True, verbose_name='Backup Date')),
                ('backup_size', models.BigIntegerField(blank=True, null=True, verbose_name='Backup Declared Size')),
                ('storage_left', models.BigIntegerField(blank=True, null=True, verbose_name='Storage Left on Device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='dashboard.backup')),
            ],
            options={
                'verbose_name': 'Backup Metadata',
                'verbose_name_plural': 'Backup Metadata',
            },
        ),
    ]
