# Generated by Django 5.1.7 on 2025-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_backupmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='service_type',
            field=models.CharField(blank=True, help_text='The service used for the message (e.g., SMS, iMessage)', max_length=20, null=True, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='device_brand',
            field=models.CharField(blank=True, choices=[('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('ios', 'IOS'), ('other', 'Other')], max_length=255, null=True, verbose_name='Device Brand'),
        ),
    ]
