# Generated by Django 5.1.7 on 2025-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-creation_date', '-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Original Creation Date'),
        ),
    ]
