# Generated by Django 5.1.7 on 2025-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_note_options_note_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='pin',
        ),
        migrations.AddField(
            model_name='backup',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
