# Generated by Django 5.1.7 on 2025-09-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_backup_pin_backup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSHomeScreenLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_version', models.IntegerField(help_text='Version number from IconState.plist', null=True, verbose_name='Widget Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ios_home_screen_layout', to='dashboard.backup', verbose_name='Backup')),
            ],
            options={
                'verbose_name': 'iOS Home Screen Layout',
                'verbose_name_plural': 'iOS Home Screen Layouts',
            },
        ),
        migrations.CreateModel(
            name='IOSHomeScreenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('APP', 'Application'), ('FOLDER', 'Folder'), ('WIDGET_STACK', 'Widget Stack')], max_length=20, verbose_name='Item Type')),
                ('location', models.CharField(choices=[('HOME_SCREEN', 'Home Screen'), ('DOCK', 'Dock')], max_length=20, verbose_name='Location')),
                ('page_index', models.IntegerField(verbose_name='Page Index')),
                ('position_on_page', models.PositiveIntegerField(help_text='The original 0-indexed order of the item within its page or folder list.', verbose_name='Position (Order) on Page')),
                ('x', models.IntegerField(help_text='Calculated column position on the grid.', null=True, verbose_name='Calculated X Position')),
                ('y', models.IntegerField(help_text='Calculated row position on the grid.', null=True, verbose_name='Calculated Y Position')),
                ('span_x', models.PositiveIntegerField(default=1, help_text='How many columns the item occupies.', verbose_name='Span X')),
                ('span_y', models.PositiveIntegerField(default=1, help_text='How many rows the item occupies.', verbose_name='Span Y')),
                ('bundle_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bundle Identifier')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Folder Display Name')),
                ('grid_size', models.CharField(blank=True, choices=[('small', 'Small (2x2)'), ('medium', 'Medium (4x2)'), ('large', 'Large (4x4)')], max_length=10, null=True, verbose_name='Grid Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('parent_folder', models.ForeignKey(blank=True, help_text='The folder that contains this item, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='dashboard.ioshomescreenitem', verbose_name='Parent Folder')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.ioshomescreenlayout', verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'iOS Home Screen Item',
                'verbose_name_plural': 'iOS Home Screen Items',
                'ordering': ['location', 'page_index', 'position_on_page'],
            },
        ),
        migrations.CreateModel(
            name='IOSWidgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_stack', models.PositiveIntegerField(verbose_name='Position in Stack')),
                ('bundle_identifier', models.CharField(max_length=255, verbose_name='Bundle Identifier')),
                ('widget_kind', models.CharField(help_text='e.g., com.apple.weather.widget', max_length=255, verbose_name='Widget Kind / Type')),
                ('stack', models.ForeignKey(limit_choices_to={'item_type': 'WIDGET_STACK'}, on_delete=django.db.models.deletion.CASCADE, related_name='widgets_in_stack', to='dashboard.ioshomescreenitem', verbose_name='Widget Stack')),
            ],
            options={
                'verbose_name': 'iOS Widget Item',
                'verbose_name_plural': 'iOS Widget Items',
                'ordering': ['position_in_stack'],
            },
        ),
    ]
