# Generated by Django 5.1.7 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_ioshomescreenlayout_ioshomescreenitem_ioswidgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioshomescreenitem',
            name='title',
            field=models.CharField(blank=True, help_text='The user-friendly name of the application.', max_length=255, null=True, verbose_name='App Title'),
        ),
    ]
