# Generated by Django 5.1.7 on 2025-09-19 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_iosnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(help_text="The list the reminder belongs to, e.g., 'Shopping' or 'Work'.", max_length=255, verbose_name='List Name')),
                ('title', models.TextField(verbose_name='Title')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('priority', models.IntegerField(choices=[(0, 'None'), (1, 'High'), (5, 'Medium'), (9, 'Low')], default=0, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='dashboard.backup')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['list_name', 'creation_date'],
            },
        ),
    ]
