# Generated by Django 5.1.7 on 2025-12-05 14:47

import dashboard.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='device_brand',
            field=models.CharField(blank=True, choices=[('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('ios', 'IOS'), ('android', 'Android'), ('other', 'Other')], max_length=255, null=True, verbose_name='Device Brand'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=functools.partial(dashboard.models.get_backup_relative_upload_path, *(), **{'subfolder': 'files'}), verbose_name='File Content'),
        ),
    ]
